services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8081:3000"
    depends_on:
      - backend
    networks:
      - task-board-network
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8082:5000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - task-board-network
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456789
      - POSTGRES_DB=task_board
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - task-board-network
volumes:
  postgres_data:
    driver: local
networks:
  task-board-network:
    driver: bridge
